baseURL = "https://cjolowicz.github.io/"
languageCode = "en-us"
title = "Claudio Jolowicz's website"
theme = "coder"

paginate = 20
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

# disqusShortname = "cjolowicz"
googleAnalytics = "UA-141256188-1"

[params]
    author = "Claudio Jolowicz"
    info = ""
    description = "Claudio Jolowicz's website"
    keywords = "blog,developer,personal"
    avatarurl = "/images/avatar.jpg"

    favicon_32 = "/images/favicon-32x32.png"
    favicon_16 = "/images/favicon-16x16.png"

    footerContent = ""

    hideCredits = true
    hideCopyright = true

    rtl = false

    math = true

[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/cjolowicz/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 2
    url = "https://twitter.com/cjolowicz/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 3
    url = "https://medium.com/@cjolowicz"

[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Music"
    weight = 2
    url = "http://claudiojolowicz.com/"
